// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//for libp2p requests on the a8 network
type A8Message struct {
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CallId    string `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Types that are valid to be assigned to Call:
	//	*A8Message_A8Request
	//	*A8Message_A8Response
	Call                 isA8Message_Call `protobuf_oneof:"call"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *A8Message) Reset()         { *m = A8Message{} }
func (m *A8Message) String() string { return proto.CompactTextString(m) }
func (*A8Message) ProtoMessage()    {}
func (*A8Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *A8Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_A8Message.Unmarshal(m, b)
}
func (m *A8Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_A8Message.Marshal(b, m, deterministic)
}
func (m *A8Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_A8Message.Merge(m, src)
}
func (m *A8Message) XXX_Size() int {
	return xxx_messageInfo_A8Message.Size(m)
}
func (m *A8Message) XXX_DiscardUnknown() {
	xxx_messageInfo_A8Message.DiscardUnknown(m)
}

var xxx_messageInfo_A8Message proto.InternalMessageInfo

func (m *A8Message) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *A8Message) GetCallId() string {
	if m != nil {
		return m.CallId
	}
	return ""
}

type isA8Message_Call interface {
	isA8Message_Call()
}

type A8Message_A8Request struct {
	A8Request *A8Request `protobuf:"bytes,3,opt,name=a8_request,json=a8Request,proto3,oneof"`
}

type A8Message_A8Response struct {
	A8Response *A8Response `protobuf:"bytes,4,opt,name=a8_response,json=a8Response,proto3,oneof"`
}

func (*A8Message_A8Request) isA8Message_Call() {}

func (*A8Message_A8Response) isA8Message_Call() {}

func (m *A8Message) GetCall() isA8Message_Call {
	if m != nil {
		return m.Call
	}
	return nil
}

func (m *A8Message) GetA8Request() *A8Request {
	if x, ok := m.GetCall().(*A8Message_A8Request); ok {
		return x.A8Request
	}
	return nil
}

func (m *A8Message) GetA8Response() *A8Response {
	if x, ok := m.GetCall().(*A8Message_A8Response); ok {
		return x.A8Response
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*A8Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*A8Message_A8Request)(nil),
		(*A8Message_A8Response)(nil),
	}
}

//packaging a request made of an EN
type A8Request struct {
	//transaction and signature can be blank for non-secure requests
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Signature   []byte       `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*A8Request_Invoke
	//	*A8Request_Deploy
	//	*A8Request_Show
	Request              isA8Request_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *A8Request) Reset()         { *m = A8Request{} }
func (m *A8Request) String() string { return proto.CompactTextString(m) }
func (*A8Request) ProtoMessage()    {}
func (*A8Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *A8Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_A8Request.Unmarshal(m, b)
}
func (m *A8Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_A8Request.Marshal(b, m, deterministic)
}
func (m *A8Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_A8Request.Merge(m, src)
}
func (m *A8Request) XXX_Size() int {
	return xxx_messageInfo_A8Request.Size(m)
}
func (m *A8Request) XXX_DiscardUnknown() {
	xxx_messageInfo_A8Request.DiscardUnknown(m)
}

var xxx_messageInfo_A8Request proto.InternalMessageInfo

func (m *A8Request) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *A8Request) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type isA8Request_Request interface {
	isA8Request_Request()
}

type A8Request_Invoke struct {
	Invoke *InvokeRequest `protobuf:"bytes,4,opt,name=invoke,proto3,oneof"`
}

type A8Request_Deploy struct {
	Deploy *FnData `protobuf:"bytes,5,opt,name=deploy,proto3,oneof"`
}

type A8Request_Show struct {
	Show *ShowRequest `protobuf:"bytes,6,opt,name=show,proto3,oneof"`
}

func (*A8Request_Invoke) isA8Request_Request() {}

func (*A8Request_Deploy) isA8Request_Request() {}

func (*A8Request_Show) isA8Request_Request() {}

func (m *A8Request) GetRequest() isA8Request_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *A8Request) GetInvoke() *InvokeRequest {
	if x, ok := m.GetRequest().(*A8Request_Invoke); ok {
		return x.Invoke
	}
	return nil
}

func (m *A8Request) GetDeploy() *FnData {
	if x, ok := m.GetRequest().(*A8Request_Deploy); ok {
		return x.Deploy
	}
	return nil
}

func (m *A8Request) GetShow() *ShowRequest {
	if x, ok := m.GetRequest().(*A8Request_Show); ok {
		return x.Show
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*A8Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*A8Request_Invoke)(nil),
		(*A8Request_Deploy)(nil),
		(*A8Request_Show)(nil),
	}
}

//packaging EN response
//decide if we want FNData has a value here instead of DeployResponse
//todo decide this with the flow.
type A8Response struct {
	// Types that are valid to be assigned to Response:
	//	*A8Response_Invoke
	//	*A8Response_Deploy
	//	*A8Response_Show
	//	*A8Response_Error
	Response             isA8Response_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *A8Response) Reset()         { *m = A8Response{} }
func (m *A8Response) String() string { return proto.CompactTextString(m) }
func (*A8Response) ProtoMessage()    {}
func (*A8Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *A8Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_A8Response.Unmarshal(m, b)
}
func (m *A8Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_A8Response.Marshal(b, m, deterministic)
}
func (m *A8Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_A8Response.Merge(m, src)
}
func (m *A8Response) XXX_Size() int {
	return xxx_messageInfo_A8Response.Size(m)
}
func (m *A8Response) XXX_DiscardUnknown() {
	xxx_messageInfo_A8Response.DiscardUnknown(m)
}

var xxx_messageInfo_A8Response proto.InternalMessageInfo

type isA8Response_Response interface {
	isA8Response_Response()
}

type A8Response_Invoke struct {
	Invoke *InvokeResponse `protobuf:"bytes,1,opt,name=invoke,proto3,oneof"`
}

type A8Response_Deploy struct {
	Deploy *FnData `protobuf:"bytes,2,opt,name=deploy,proto3,oneof"`
}

type A8Response_Show struct {
	Show *ShowResponse `protobuf:"bytes,3,opt,name=show,proto3,oneof"`
}

type A8Response_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*A8Response_Invoke) isA8Response_Response() {}

func (*A8Response_Deploy) isA8Response_Response() {}

func (*A8Response_Show) isA8Response_Response() {}

func (*A8Response_Error) isA8Response_Response() {}

func (m *A8Response) GetResponse() isA8Response_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *A8Response) GetInvoke() *InvokeResponse {
	if x, ok := m.GetResponse().(*A8Response_Invoke); ok {
		return x.Invoke
	}
	return nil
}

func (m *A8Response) GetDeploy() *FnData {
	if x, ok := m.GetResponse().(*A8Response_Deploy); ok {
		return x.Deploy
	}
	return nil
}

func (m *A8Response) GetShow() *ShowResponse {
	if x, ok := m.GetResponse().(*A8Response_Show); ok {
		return x.Show
	}
	return nil
}

func (m *A8Response) GetError() *Error {
	if x, ok := m.GetResponse().(*A8Response_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*A8Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*A8Response_Invoke)(nil),
		(*A8Response_Deploy)(nil),
		(*A8Response_Show)(nil),
		(*A8Response_Error)(nil),
	}
}

//information that makes a transaction unique
type Transaction struct {
	Nonce                string   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	NodeId               string   `protobuf:"bytes,3,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Transaction) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Transaction) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type InvokeRequest struct {
	Fqn                  string   `protobuf:"bytes,1,opt,name=fqn,proto3" json:"fqn,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=Input,proto3" json:"Input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeRequest) Reset()         { *m = InvokeRequest{} }
func (m *InvokeRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeRequest) ProtoMessage()    {}
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *InvokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeRequest.Unmarshal(m, b)
}
func (m *InvokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeRequest.Marshal(b, m, deterministic)
}
func (m *InvokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeRequest.Merge(m, src)
}
func (m *InvokeRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeRequest.Size(m)
}
func (m *InvokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeRequest proto.InternalMessageInfo

func (m *InvokeRequest) GetFqn() string {
	if m != nil {
		return m.Fqn
	}
	return ""
}

func (m *InvokeRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type InvokeResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeResponse) Reset()         { *m = InvokeResponse{} }
func (m *InvokeResponse) String() string { return proto.CompactTextString(m) }
func (*InvokeResponse) ProtoMessage()    {}
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *InvokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeResponse.Unmarshal(m, b)
}
func (m *InvokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeResponse.Marshal(b, m, deterministic)
}
func (m *InvokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeResponse.Merge(m, src)
}
func (m *InvokeResponse) XXX_Size() int {
	return xxx_messageInfo_InvokeResponse.Size(m)
}
func (m *InvokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeResponse proto.InternalMessageInfo

func (m *InvokeResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InvokeResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type FnData struct {
	Fqn                  string   `protobuf:"bytes,1,opt,name=fqn,proto3" json:"fqn,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Memory               int32    `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Timeout              int32    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	IdleTimeout          int32    `protobuf:"varint,5,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	Audit                *Audit   `protobuf:"bytes,6,opt,name=audit,proto3" json:"audit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FnData) Reset()         { *m = FnData{} }
func (m *FnData) String() string { return proto.CompactTextString(m) }
func (*FnData) ProtoMessage()    {}
func (*FnData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *FnData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FnData.Unmarshal(m, b)
}
func (m *FnData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FnData.Marshal(b, m, deterministic)
}
func (m *FnData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FnData.Merge(m, src)
}
func (m *FnData) XXX_Size() int {
	return xxx_messageInfo_FnData.Size(m)
}
func (m *FnData) XXX_DiscardUnknown() {
	xxx_messageInfo_FnData.DiscardUnknown(m)
}

var xxx_messageInfo_FnData proto.InternalMessageInfo

func (m *FnData) GetFqn() string {
	if m != nil {
		return m.Fqn
	}
	return ""
}

func (m *FnData) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *FnData) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *FnData) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *FnData) GetIdleTimeout() int32 {
	if m != nil {
		return m.IdleTimeout
	}
	return 0
}

func (m *FnData) GetAudit() *Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

type ShowRequest struct {
	Ns                   string   `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRequest) Reset()         { *m = ShowRequest{} }
func (m *ShowRequest) String() string { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()    {}
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}

func (m *ShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRequest.Unmarshal(m, b)
}
func (m *ShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRequest.Marshal(b, m, deterministic)
}
func (m *ShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRequest.Merge(m, src)
}
func (m *ShowRequest) XXX_Size() int {
	return xxx_messageInfo_ShowRequest.Size(m)
}
func (m *ShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRequest proto.InternalMessageInfo

func (m *ShowRequest) GetNs() string {
	if m != nil {
		return m.Ns
	}
	return ""
}

type ShowResponse struct {
	// Types that are valid to be assigned to Response:
	//	*ShowResponse_FnFunctionData
	//	*ShowResponse_NamespaceList
	Response             isShowResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ShowResponse) Reset()         { *m = ShowResponse{} }
func (m *ShowResponse) String() string { return proto.CompactTextString(m) }
func (*ShowResponse) ProtoMessage()    {}
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8}
}

func (m *ShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowResponse.Unmarshal(m, b)
}
func (m *ShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowResponse.Marshal(b, m, deterministic)
}
func (m *ShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowResponse.Merge(m, src)
}
func (m *ShowResponse) XXX_Size() int {
	return xxx_messageInfo_ShowResponse.Size(m)
}
func (m *ShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowResponse proto.InternalMessageInfo

type isShowResponse_Response interface {
	isShowResponse_Response()
}

type ShowResponse_FnFunctionData struct {
	FnFunctionData *FnData `protobuf:"bytes,1,opt,name=fn_function_data,json=fnFunctionData,proto3,oneof"`
}

type ShowResponse_NamespaceList struct {
	NamespaceList *NamespaceList `protobuf:"bytes,2,opt,name=namespace_list,json=namespaceList,proto3,oneof"`
}

func (*ShowResponse_FnFunctionData) isShowResponse_Response() {}

func (*ShowResponse_NamespaceList) isShowResponse_Response() {}

func (m *ShowResponse) GetResponse() isShowResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ShowResponse) GetFnFunctionData() *FnData {
	if x, ok := m.GetResponse().(*ShowResponse_FnFunctionData); ok {
		return x.FnFunctionData
	}
	return nil
}

func (m *ShowResponse) GetNamespaceList() *NamespaceList {
	if x, ok := m.GetResponse().(*ShowResponse_NamespaceList); ok {
		return x.NamespaceList
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ShowResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ShowResponse_FnFunctionData)(nil),
		(*ShowResponse_NamespaceList)(nil),
	}
}

//oneof cannot have repeated as a modifier of an entry, so we are wrapping the one of in a list message
type NamespaceList struct {
	List                 []*NamespaceData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NamespaceList) Reset()         { *m = NamespaceList{} }
func (m *NamespaceList) String() string { return proto.CompactTextString(m) }
func (*NamespaceList) ProtoMessage()    {}
func (*NamespaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9}
}

func (m *NamespaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceList.Unmarshal(m, b)
}
func (m *NamespaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceList.Marshal(b, m, deterministic)
}
func (m *NamespaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceList.Merge(m, src)
}
func (m *NamespaceList) XXX_Size() int {
	return xxx_messageInfo_NamespaceList.Size(m)
}
func (m *NamespaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceList.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceList proto.InternalMessageInfo

func (m *NamespaceList) GetList() []*NamespaceData {
	if m != nil {
		return m.List
	}
	return nil
}

type NamespaceData struct {
	NamespaceName        string   `protobuf:"bytes,1,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
	Audit                *Audit   `protobuf:"bytes,2,opt,name=audit,proto3" json:"audit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamespaceData) Reset()         { *m = NamespaceData{} }
func (m *NamespaceData) String() string { return proto.CompactTextString(m) }
func (*NamespaceData) ProtoMessage()    {}
func (*NamespaceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10}
}

func (m *NamespaceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceData.Unmarshal(m, b)
}
func (m *NamespaceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceData.Marshal(b, m, deterministic)
}
func (m *NamespaceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceData.Merge(m, src)
}
func (m *NamespaceData) XXX_Size() int {
	return xxx_messageInfo_NamespaceData.Size(m)
}
func (m *NamespaceData) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceData.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceData proto.InternalMessageInfo

func (m *NamespaceData) GetNamespaceName() string {
	if m != nil {
		return m.NamespaceName
	}
	return ""
}

func (m *NamespaceData) GetAudit() *Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

type Audit struct {
	CreatedAt            int64    `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Audit) Reset()         { *m = Audit{} }
func (m *Audit) String() string { return proto.CompactTextString(m) }
func (*Audit) ProtoMessage()    {}
func (*Audit) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{11}
}

func (m *Audit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audit.Unmarshal(m, b)
}
func (m *Audit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audit.Marshal(b, m, deterministic)
}
func (m *Audit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audit.Merge(m, src)
}
func (m *Audit) XXX_Size() int {
	return xxx_messageInfo_Audit.Size(m)
}
func (m *Audit) XXX_DiscardUnknown() {
	xxx_messageInfo_Audit.DiscardUnknown(m)
}

var xxx_messageInfo_Audit proto.InternalMessageInfo

func (m *Audit) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Audit) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{12}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*A8Message)(nil), "messages.A8message")
	proto.RegisterType((*A8Request)(nil), "messages.A8Request")
	proto.RegisterType((*A8Response)(nil), "messages.A8Response")
	proto.RegisterType((*Transaction)(nil), "messages.Transaction")
	proto.RegisterType((*InvokeRequest)(nil), "messages.InvokeRequest")
	proto.RegisterType((*InvokeResponse)(nil), "messages.InvokeResponse")
	proto.RegisterType((*FnData)(nil), "messages.FnData")
	proto.RegisterType((*ShowRequest)(nil), "messages.ShowRequest")
	proto.RegisterType((*ShowResponse)(nil), "messages.ShowResponse")
	proto.RegisterType((*NamespaceList)(nil), "messages.NamespaceList")
	proto.RegisterType((*NamespaceData)(nil), "messages.NamespaceData")
	proto.RegisterType((*Audit)(nil), "messages.Audit")
	proto.RegisterType((*Error)(nil), "messages.Error")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 674 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xc1, 0x4e, 0xdb, 0x40,
	0x10, 0xc5, 0x49, 0x6c, 0xf0, 0x24, 0xa4, 0x68, 0x4b, 0x21, 0x87, 0x22, 0x81, 0x25, 0x54, 0xd4,
	0x56, 0x48, 0xa5, 0x95, 0xc8, 0x81, 0x43, 0x83, 0x0a, 0x22, 0x6a, 0xc5, 0x61, 0xcb, 0xa9, 0x52,
	0x65, 0x2d, 0xf1, 0x06, 0x2c, 0x92, 0x5d, 0xe3, 0x5d, 0x17, 0xe5, 0x57, 0xfa, 0x0d, 0xfd, 0x82,
	0xfe, 0x44, 0xbf, 0xa7, 0xb7, 0x6a, 0x67, 0xd7, 0xb1, 0x03, 0xb4, 0xbd, 0xed, 0x9b, 0x37, 0x33,
	0xfb, 0xfc, 0x66, 0xd6, 0xd0, 0x9d, 0x72, 0xa5, 0xd8, 0x15, 0x57, 0xfb, 0x59, 0x2e, 0xb5, 0x24,
	0x2b, 0x25, 0x8e, 0x7e, 0x7a, 0x10, 0x0e, 0xfa, 0x0e, 0x92, 0x2d, 0x00, 0x77, 0x8c, 0xd3, 0xa4,
	0xe7, 0x6d, 0x7b, 0x7b, 0x21, 0x0d, 0x5d, 0x64, 0x98, 0x90, 0x4d, 0x58, 0x1e, 0xb1, 0xc9, 0xc4,
	0x70, 0x0d, 0xe4, 0x02, 0x03, 0x87, 0x09, 0x79, 0x07, 0xc0, 0xfa, 0x71, 0xce, 0x6f, 0x0b, 0xae,
	0x74, 0xaf, 0xb9, 0xed, 0xed, 0xb5, 0x0f, 0x9e, 0xee, 0xcf, 0x2f, 0x1d, 0xf4, 0xa9, 0xa5, 0xce,
	0x96, 0x68, 0xc8, 0x4a, 0x40, 0x0e, 0xa1, 0x8d, 0x55, 0x2a, 0x93, 0x42, 0xf1, 0x5e, 0x0b, 0xcb,
	0xd6, 0x17, 0xcb, 0x2c, 0x77, 0xb6, 0x44, 0x81, 0xcd, 0xd1, 0x71, 0x00, 0x2d, 0x73, 0x71, 0xf4,
	0x1b, 0xc5, 0xd7, 0xda, 0xe9, 0x9c, 0x09, 0xc5, 0x46, 0x3a, 0x95, 0x02, 0xd5, 0xb7, 0x0f, 0x9e,
	0x55, 0xed, 0x2e, 0x2a, 0x92, 0xd6, 0x33, 0xc9, 0x73, 0x08, 0x55, 0x7a, 0x25, 0x98, 0x2e, 0x72,
	0x8e, 0x1f, 0xd6, 0xa1, 0x55, 0x80, 0xbc, 0x81, 0x20, 0x15, 0xdf, 0xe4, 0x4d, 0x29, 0x70, 0xb3,
	0xea, 0x38, 0xc4, 0x78, 0xf5, 0x6d, 0x2e, 0x91, 0xbc, 0x84, 0x20, 0xe1, 0xd9, 0x44, 0xce, 0x7a,
	0x3e, 0x96, 0xac, 0x55, 0x25, 0xa7, 0xe2, 0x03, 0xd3, 0xcc, 0xe4, 0xda, 0x0c, 0xf2, 0x0a, 0x5a,
	0xea, 0x5a, 0xde, 0xf5, 0x82, 0xfb, 0x72, 0x3f, 0x5f, 0xcb, 0xbb, 0xaa, 0x35, 0x26, 0x1d, 0x87,
	0xb0, 0xec, 0x4c, 0x8e, 0x7e, 0x79, 0x00, 0x95, 0x41, 0xe4, 0x60, 0xae, 0xd2, 0x7e, 0x77, 0xef,
	0xa1, 0xca, 0xb9, 0x95, 0x0f, 0x65, 0x36, 0xfe, 0x2b, 0xf3, 0xb5, 0x93, 0x69, 0x67, 0xbb, 0x71,
	0x5f, 0xe6, 0xbc, 0x37, 0x66, 0x91, 0x17, 0xe0, 0xf3, 0x3c, 0x97, 0xb9, 0xb3, 0xec, 0x49, 0x95,
	0x7e, 0x62, 0xc2, 0x67, 0x4b, 0xd4, 0xf2, 0xc7, 0x00, 0x2b, 0xe5, 0xfc, 0xa3, 0x2f, 0xd0, 0xae,
	0x8d, 0x88, 0xac, 0x83, 0x2f, 0xa4, 0x18, 0x71, 0xb7, 0x86, 0x16, 0x98, 0x0d, 0xcd, 0x8a, 0xcb,
	0x49, 0x3a, 0x8a, 0x6f, 0xf8, 0xcc, 0x6d, 0x61, 0x68, 0x23, 0x1f, 0xf9, 0x8c, 0x6c, 0x40, 0x70,
	0x2e, 0x13, 0x3e, 0x4c, 0x50, 0x68, 0x48, 0x1d, 0x8a, 0x0e, 0x61, 0x75, 0x61, 0x58, 0x64, 0x0d,
	0x9a, 0xe3, 0x5b, 0xe1, 0x7a, 0x9b, 0xa3, 0xb9, 0x6f, 0x28, 0xb2, 0x42, 0xbb, 0xa6, 0x16, 0x44,
	0x7d, 0xe8, 0x2e, 0xfa, 0x47, 0x08, 0xb4, 0x12, 0xa6, 0x19, 0x96, 0x76, 0x28, 0x9e, 0x4d, 0x4c,
	0xcf, 0x32, 0xee, 0x4a, 0xf1, 0x1c, 0xfd, 0xf0, 0x20, 0xb0, 0x36, 0x3e, 0x7e, 0x59, 0x3a, 0x65,
	0x57, 0x65, 0x85, 0x05, 0x46, 0xfd, 0x94, 0x4f, 0x65, 0x3e, 0x43, 0xf5, 0x3e, 0x75, 0x88, 0xf4,
	0x60, 0x59, 0xa7, 0x53, 0x2e, 0x0b, 0x8d, 0x86, 0xfa, 0xb4, 0x84, 0x64, 0x07, 0x3a, 0x69, 0x32,
	0xe1, 0x71, 0x49, 0xfb, 0x48, 0xb7, 0x4d, 0xec, 0xc2, 0xa5, 0xec, 0x82, 0xcf, 0x8a, 0x24, 0xd5,
	0x6e, 0xc3, 0x6a, 0xb3, 0x18, 0x98, 0x30, 0xb5, 0x6c, 0xb4, 0x05, 0xed, 0xda, 0xc6, 0x91, 0x2e,
	0x34, 0x84, 0x72, 0x8a, 0x1b, 0x42, 0x45, 0xdf, 0x3d, 0xe8, 0xd4, 0x47, 0x4d, 0x8e, 0x60, 0x6d,
	0x2c, 0xe2, 0x71, 0x21, 0x70, 0x5a, 0xf1, 0xdc, 0x92, 0xc7, 0xd7, 0xa8, 0x3b, 0x16, 0xa7, 0x2e,
	0x15, 0x1d, 0x79, 0x0f, 0x5d, 0xc1, 0xa6, 0x5c, 0x65, 0x6c, 0xc4, 0xe3, 0x49, 0xaa, 0xb4, 0x5b,
	0xc1, 0xda, 0xe3, 0x3a, 0x2f, 0xf9, 0x4f, 0x29, 0xbe, 0x80, 0x55, 0x51, 0x0f, 0x2c, 0x6c, 0xce,
	0x11, 0xac, 0x2e, 0x64, 0x9b, 0x47, 0x85, 0x4d, 0xbd, 0xed, 0xe6, 0x5f, 0x9a, 0x1a, 0x15, 0x14,
	0x93, 0xa2, 0xaf, 0xb5, 0x6a, 0x14, 0xb7, 0x5b, 0x17, 0x67, 0x4e, 0xce, 0x87, 0x4a, 0x81, 0xc9,
	0xaf, 0x8c, 0x6d, 0xfc, 0xd3, 0xd8, 0x13, 0xf0, 0x11, 0x9b, 0xd5, 0x1d, 0xe5, 0x9c, 0x69, 0x9e,
	0xc4, 0x4c, 0x63, 0xcb, 0x26, 0x0d, 0x5d, 0x64, 0x80, 0x74, 0x91, 0x25, 0x25, 0xdd, 0xb0, 0xb4,
	0x8b, 0x0c, 0x74, 0xb4, 0x03, 0x3e, 0xbe, 0x1d, 0xb3, 0x0c, 0xee, 0x22, 0x27, 0xab, 0x84, 0x97,
	0x01, 0xfe, 0xdc, 0xdf, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x94, 0x0a, 0xfb, 0x6f, 0xee, 0x05,
	0x00, 0x00,
}
